# Generated by Django 5.2.12 on 2026-03-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Anonymous', max_length=50, verbose_name='Player Name')),
                ('time_seconds', models.FloatField(verbose_name='Time (seconds)')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10, verbose_name='Difficulty')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['time_seconds'],
            },
        ),
    ]
